/*
 * generated by Xtext
 */
package org.xtext.tesis;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SALRuntimeModule extends org.xtext.tesis.AbstractSALRuntimeModule {

}
