/*
* generated by Xtext
*/
package org.xtext.tesis;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SALStandaloneSetup extends SALStandaloneSetupGenerated{

	public static void doSetup() {
		new SALStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

