/**
 * generated by Xtext
 */
package org.xtext.tesis.ui.contentassist;

import org.xtext.tesis.ui.contentassist.AbstractSALProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SALProposalProvider extends AbstractSALProposalProvider {
}
