/*
 * generated by Xtext
 */
package org.xtext.tesis.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SALUiModule extends org.xtext.tesis.ui.AbstractSALUiModule {
	public SALUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
