/**
 * generated by Xtext
 */
package org.xtext.tesis.validation;

import org.xtext.tesis.validation.AbstractSALValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SALValidator extends AbstractSALValidator {
}
