/*
* generated by Xtext
*/
package org.xtext.tesis.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.tesis.services.SALGrammarAccess;

public class SALParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SALGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.tesis.parser.antlr.internal.InternalSALParser createParser(XtextTokenStream stream) {
		return new org.xtext.tesis.parser.antlr.internal.InternalSALParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Context";
	}
	
	public SALGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SALGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
