/*
* generated by Xtext
*/
package org.xtext.tesis;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SALUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.tesis.ui.internal.SALActivator.getInstance().getInjector("org.xtext.tesis.SAL");
	}
	
}
